kind = "web"
previewPath = "/"
title = "Retrusty"
version = "1.0.0"
id = "artifacts/retrusty"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23468

[services.development]
run = "pnpm --filter @workspace/retrusty run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/retrusty", "run", "build" ]
publicDir = "artifacts/retrusty/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23468"
BASE_PATH = "/"
